# Generated by Django 4.2.7 on 2023-12-03 21:57

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="note",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
