# Generated by Django 4.2.7 on 2023-12-03 22:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_note_options_note_created_note_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="notes.topic",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="rght",
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=3, editable=False),
            preserve_default=False,
        ),
    ]
