# Generated by Django 4.2.7 on 2023-12-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_topic_level_topic_lft_topic_parent_topic_rght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
